### ISSUE TITLE
Option to hide the title

### ISSUE THREAD

**Issue by depaege** [decompil3d/lovelace-hourly-weather#551] opened 2023-10-18 20:07 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to hide the title. Now the title is displayed in a large font and it takes a lot of space. It would be nice to have a compact card. It is quite clear what the card represents, so a title is not always necessary. Thanks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by decompil3d** [comment] 2023-10-18 23:35
Duplicate of #214. Use `name: null` in YAML to accomplish this.

**Closed by decompil3d** 2023-10-18 23:35 UTC
