### ISSUE TITLE
Stopped working with MetOffice weather integration.

### ISSUE THREAD

**Issue by Ben00793** [decompil3d/lovelace-hourly-weather#668] opened 2024-04-22 10:50 UTC
I was using this card with my MetOffice weather integration for a while now.
Today the card just disappeared from my dashboard.
It's only works if i use the weather.forecast_home (standard home assistant) integration

**Comment by DaGhostDS** [comment] 2024-07-04 21:27
Also stopped working with Environment Canada Integration with the message :

  **_Forecast not available  
  Check the configured forecast entity._**
  
  I checked and yeah it also work on the default "Weather.forecast_home".
  
I checked Yesterday patch notes and it says they deprecated "get_forecast" and use "get_forecasts" instead.

https://github.com/home-assistant/core/pull/118664

**Comment by decompil3d** [comment] 2024-07-04 22:55
Please make sure you've upgraded to the latest version of the card. The `get_forecast(s)` fix is in there. Let me know if you still have problems after that.

**Comment by DaGhostDS** [comment] 2024-07-04 23:17
Same issue, first thing I did before posting about the issue is updating.

**Comment by mrfrag1** [comment] 2024-07-05 07:47
Hi, same issue after updating to HA 2024.7

<img width="298" alt="image" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/108211193/2d1a3eba-5c91-4716-9d39-c1ae4fc58472">

Your card ist the latest version. The entity is ok:

<img width="646" alt="image" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/108211193/e5ce6b3f-cff4-442b-9e4a-79f2da6f11a8">

**Comment by cerebrate** [comment] 2024-07-05 17:42
I'm having this issue now for the first time post-update to 2024.7; the source of the weather entity is Tomorrow.io, and an examination of the entity shows that it does include hourly forecast data.

**Comment by decompil3d** [comment] 2024-07-06 15:00
Thanks for all the reports, folks. I'm away from my computer this weekend but I'll look at this on Monday. I thought I had fixed this in 6.0.2 and tested with 2024.7b1 but apparently something else needs fixing too. Apologies for the inconvenience.

**Comment by DaGhostDS** [comment] 2024-07-07 15:56
> Thanks for all the reports, folks. I'm away from my computer this weekend but I'll look at this on Monday. I thought I had fixed this in 6.0.2 and tested with 2024.7b1 but apparently something else needs fixing too. Apologies for the inconvenience.

Seem you might have, on Chrome, Edge and the Android app started working with the Friday HASS update, but it still refused to show on my Firefox.

I had to purge the cache by "Forget about this site.." in history.

Thanks!

**Comment by Valdorama** [comment] 2024-07-08 16:31
Thanks @DaGhostDS , after deleting cache on Chrome on a desktop, it's working again.

**Comment by decompil3d** [comment] 2024-07-18 17:41
Sounds like this works fine with a re-download. If the MetOffice integration is still busted, feel free to reopen or comment here.

**Closed by decompil3d** 2024-07-18 17:41 UTC
Labels: bug
