### ISSUE TITLE
day in the middle of the night

### ISSUE THREAD

**Issue by Santanachia** [decompil3d/lovelace-hourly-weather#519] opened 2023-09-20 13:00 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.1.0

**Last working release (if known):**

**Browser and Operating System:**
Irrelevant 

**Description of problem:**

A cloudy night should have a dark background as opposed to a cloudy day.
At the moment it looks like this:
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/4628507/644a7b16-aa66-4389-aaec-457267e1f66e)

**Javascript errors shown in the web inspector (if applicable):**
**Additional information:**

**Comment by decompil3d** [comment] 2023-09-20 14:23
This is a duplicate of #122.

Unfortunately, Home Assistant does not provide data for whether it's day or night in forecasts. Just conditions. For current weather, we can look at current sun state, but long term sunrise/set isn't available.

Having looked at Home Assistant internals lately, I think there's a possibility that this gets addressed there at some point soon. But as of 2023.9, it is not supported.

Sorry 🙁

**Closed by decompil3d** 2023-09-20 14:23 UTC
Labels: bug

**Comment by Santanachia** [comment] 2023-09-20 14:59
Sunset/sunrise sensor as parameter?

**Comment by decompil3d** [comment] 2023-09-20 15:54
The issue is that those sensors would only give you current day sunrise and sunset. For this, we'd need arbitrary day information. There's some code in HA Core that looks like we may eventually have an `is_daytime` flag on forecasts. But it's not plumbed through yet.

**Comment by decompil3d** [comment] 2023-09-20 15:59
Ah, I stand corrected: the `is_daytime` flag is for twice daily forecasts, not for this purpose. Unfortunately, I think we would need broader support for a sunrise sunset calculation on arbitrary days to address this.

**Comment by decompil3d** [comment] 2023-09-20 16:01
One possible option is to contribute to the HA Core Sun integration to add a service that provides sunrise sunset times for a given day. I know that the internals of that integration can calculate that, but it's just not exposed.

**Comment by Santanachia** [comment] 2023-09-20 17:40
Using todays sunrise/sunset would be better than nothing
